name: competitive
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  provider:
  cloud_firestore: ^4.13.0
  cached_network_image: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
      android: "ic_launcher"
      ios: true
      image_path: "assets/images/INx.png"
      min_sdk_android: 21 # android min sdk min:16, default 21



flutter:

  uses-material-design: true

  assets:
     - assets/images/

