// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3zi0MkMVV9YTwz7mXEbI0w5kA2zPyps',
    appId: '1:476322931060:web:ced0c597cc8ac6b2be8c21',
    messagingSenderId: '476322931060',
    projectId: 'competitive-chatting',
    authDomain: 'competitive-chatting.firebaseapp.com',
    storageBucket: 'competitive-chatting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChjmtcKwSD-d1DsFXwiNMDxu0N8ACnEE4',
    appId: '1:476322931060:android:e55a73ce1916e317be8c21',
    messagingSenderId: '476322931060',
    projectId: 'competitive-chatting',
    storageBucket: 'competitive-chatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6z4qraaNPC2m0fWR8_sB-b1coR3LlBCQ',
    appId: '1:476322931060:ios:0365d4ed8981bae6be8c21',
    messagingSenderId: '476322931060',
    projectId: 'competitive-chatting',
    storageBucket: 'competitive-chatting.appspot.com',
    iosBundleId: 'com.example.competitive',
  );
}
